### ISSUE TITLE
idea: monolithic executables with chez-exe

### ISSUE THREAD

**Issue by diakopter** [edwinb/Idris2-boot#11]
see [gwatt/chez-exe](https://github.com/gwatt/chez-exe)

Would it be neat to be able to "compile" idris2 programs to monolithic executables (by bundling the idris2 runtime/libraries and the user's script/packages and chez scheme)?

Creating this issue in case there is interest, to be studied in the future

**Comment by edwinb** [comment]
It would be neat, but I'd prefer to keep the issue tracker for concrete issues than potential project or implementation ideas that won't necessarily get done. Just to keep control of my own workload/time management, I'd like to keep the scope of the core as small as is reasonable.

Maybe we should have a wiki page for this sort of thing (the wiki is currently empty) and point at it from CONTRIBUTING.md.

At some stage, we'll have a way to write new back ends as plugins, similar to the way it worked in Idris 1, so that we can keep the default as simple as possible.
