### ISSUE TITLE
Can't solve constraint

### ISSUE THREAD

**Issue by nicolabotta** [edwinb/Idris2-boot#120]
The program
```
import Data.So

public export
total
soOrIntro1 : (b1 : Bool) -> (b2 : Bool) -> So b1 -> So (b1 || b2)
soOrIntro1 True _  Oh = Oh

public export
total
LTinLTE : {x, y : Double} -> So (x < y) -> So (x <= y)
LTinLTE {x} {y} prf = soOrIntro1 (x < y) (x == y) prf
```
type checks fine in Idris. However, in Idris2 one gets
```
nicola@lt561:~/gitlab/botta/Idris2Libs$ idris2 issues/CannotSolveConstraint4.idr
1/1: Building issues.CannotSolveConstraint4 (issues/CannotSolveConstraint4.idr)
issues/CannotSolveConstraint4.idr:11:23--12:1:While processing right hand side of Main.LTinLTE at issues/CannotSolveConstraint4.idr:11:1--12:1:
Can't solve constraint between:
	(x < y) || Delay (x == y)
and
	intToBool (prim__lte_Double x y)
Welcome to Idris 2 version 0.0.0.  Enjoy yourself!
Main> :q
Bye for now!
nicola@lt561:~/gitlab/botta/Idris2Libs$
```
Is this the expected behavior? Is there a canonical way of implementing LTinLTE in Idris2?

**Comment by clayrat** [comment]
It seems that in Idris2 `<=` is implemented by a primitive instead of falling back to a boolean disjunction like in Idris1, so it's unlikely that this can be proved without assertions.

**Comment by edwinb** [comment]
Hmm, yes, I think @clayrat is right here. I'm not sure what the best thing to do is here. I suppose it would be good to have a library of axioms about primitives, at the very least.

Probably the wording of this error message could be clearer too. It's really just that it can't solve the unification problem, but it's been delayed rather than failed immediately (which is an internal detail the user probably doesn't need to know)

**Comment by nicolabotta** [comment]
Right, I have started to collect some postulates in

https://gitlab.pik-potsdam.de/botta/Idris2Libs/blob/master/DoubleExtensions/Postulates.idr

and commented out those that one would use to model real number but that certainly do not hold for Double precision numbers. 

The problem is that, in order to proceed, we need access to the primitive IEEE constants (DoubleEpsilon, Inf and NaN) and I am not sure these are currently available in Idris 2.  In Haskell one would access them by importing Numeric.IEEE.

**Comment by edwinb** [comment]
I've started trying to catch up with older issues... I think this should be closed though because it is correct behaviour given how `<=` is implemented on `Double`, as a primitive. And, as a primitive, you can say `LTinLTE {x} {y} prf = believe_me Oh`

I don't know enough about IEEE floats, otherwise. Would we need to add them to Idris 1 too to get the right compile time behaviour?
