### ISSUE TITLE
unexpectedly slow auto implicit resolution

### ISSUE THREAD

**Issue by alrunner4** [edwinb/Idris2-boot#169]
Perhaps this doesn't work for some sensible reason that escapes me since this doesn't work in idris-1.3.2 either, but it does at least terminate there. I'm running `ab98b4d3c`, and loading this file sends idris2 into some sort of loop - lots of CPU usage, but no memory growth.

~Is there a reason why this theoretically can't work, or just an implementation hole at this early stage?~

Apparently I was just being impatient - this _does_ eventually compile, after about 3.25 minutes! I presume it's preferring to check all possible iterations of nesting calls to Sequence... or if are there infinitely many since you can form a cycle, why _does_ it terminate, after a while, and impressively make no dent on idris2's 64MB memory footprint?

# Steps to Reproduce
```idris
module phases

public export
data Phase = Gas | Liquid | Solid

public export
data ChangePhase : Phase -> Phase -> Type where
	Sequence : ChangePhase a b -> ChangePhase b c -> ChangePhase a c
	Condense : ChangePhase Gas Liquid
	Freeze : ChangePhase Liquid Solid
	Melt : ChangePhase Solid Liquid
	Vaporize : ChangePhase Liquid Gas
	Sublimate : ChangePhase Solid Gas

public export
inferred : { auto transition : ChangePhase l r } -> ChangePhase l r
inferred { transition } = transition

test : ChangePhase Gas Solid
test = inferred
```
# Expected Behavior
Successful search of `transition` on `inferred` within `test` as
```
Sequence Condense Freeze
```

# Observed Behavior
~File loading doesn't terminate when `inferred` is used.~
File loading takes much longer than expected when `inferred` is used.

**Comment by edwinb** [comment]
One thing Idris 2 does that Idris 1 didn't is check that there is a unique solution for an auto implicit. So the bigger the type, the more there is to check. We might not always want this though - we do for interface resolution, but sometimes you just want to know that a proof exists, which is probably what you want here. I'll have a poke at this just to be certain that's what's going on, anyway!

Search terminates because once it encounters a type its seen before, it rejects that branch. As for memory usage, I think the memory requirements of a branch in proof search aren't that much, and if it rejects a branch it's going to get garbage collected and there's no updates to the context required in any case. But I am just guessing there.

**Comment by edwinb** [comment]
I removed the ambiguity check and this resolved instantly... I'll have to think about the best way to proceed...

**Comment by alrunner4** [comment]
FWIW, I'm not really attached to the way Idris1 auto implicits will settle for first-discovered, rather than unique proof. Uniqueness seems the better default to me in general, but perhaps both have their place.
