### ISSUE TITLE
Can't find implementation for auto implicit variable

### ISSUE THREAD

**Issue by lodi** [edwinb/Idris2-boot#179]
Sorry about the non-minimal test case.  I was writing a post that works for Idris1 (1.3.2) but won't typecheck in Idris2 (bf5b229).

```
-- Let's say we have a complex data type, but in `myFn` below we're only
-- interested in handling some subset of these constructors.
data Data = Dstr String
          | Dchr Char
          | Dint Int


-- We'll use the type below as proof that some given data is in our subset of
-- interest.
data DataValid : Data -> Type where
  Dv1 : DataValid (Dstr s)
  Dv2 : DataValid (Dchr c)

Uninhabited (DataValid (Dint i)) where
  uninhabited _ impossible

total
validateData : (f : Data) -> Dec (DataValid f)
validateData (Dstr x) = Yes Dv1
validateData (Dchr x) = Yes Dv2
validateData (Dint x) = No absurd


-- Now instead of having a partial function, or a total function returning a
-- Maybe, we can handle only and exactly those cases we support.
total
myFn : (f : Data) -> {auto v : DataValid f} -> String
myFn (Dstr s) {v = Dv1} = s
myFn (Dchr c) {v = Dv2} = cast c


-- To obtain the proof, the caller can run a check...
total
caller : Data -> String
caller d =
  case validateData d of
    (Yes prf) => myFn d
    (No contra) => "error"


-- ... or just let the compiler find obvious proofs automatically.
total
caller2 : String
caller2 =
  let testValid = Dstr "Hello"
      testInvalid = Dint 5
  in
    -- won't compile: "Can't find a value of type DataValid (Dint 5)"
    -- myFn testInvalid

    myFn testValid
```

# Expected Behavior

(no errors)

# Observed Behavior

```
at line 51, character 5, file test.idr
While processing right hand side of Main.caller2 at test.idr:44:1--52:1:
Can't find an implementation for DataValid testValid
```

If supplying the implicit argument manually:

```
    myFn testValid {v=Dv1}
```

```
at line 51, character 23, file test.idr
While processing right hand side of Main.caller2 at test.idr:44:1--52:1:
When unifying DataValid (Dstr ?s) and DataValid testValid
Mismatch between:
	Dstr ?s
and
	testValid
```

I'm not sure why this is failing since `testValid = Dstr "Hello"`.

**Comment by ohad** [comment]
That's a good question, but as far as I can tell, not a bug. 
I've had similar problems in the past. The reason is that you are using let-binding which don't participate in proof search (`auto` implicits).

If you change to use type-ascribed let (also known as 'local definition'):
```
caller2 : String
caller2 =
  let testValid : Data
      testValid = Dstr "Hello"
      testInvalid : Data
      testInvalid = Dint 5
  in
    -- won't compile: "Can't find a value of type DataValid (Dint 5)"
    -- myFn testInvalid

    myFn testValid
```
This would compile.

Edwin [told me at some point](https://github.com/edwinb/Idris2/issues/107#issuecomment-536310999) that the intention is that:
1) let-binding/type-inferred lets are syntactic sugar for substituting the argument term for the argument variable in the body. Specifically:
```
let x = e in t
```
should be treated as:
```
(\ x => e) t
```

2) local definitions are syntactic sugar for declaring a new local variable (say `x`), whose value is the (normalised?) argument term, and whose scope is the body of the let. This scope also includes the substituted value for `x`, which we may use if we need to normalise a term involving `x`.

The local definition works as expected, for the reasons you expect.
The let binding doesn't work. If we desugar the let-binding, we have:
```
(\x => myFn x) (Dstr "Hello")
```
When Idris type-checks `myFn x`, all it knows is `x : Data` (and it doesn't know that `x` will be bound to `Dstr "Hello"`), and so it cannot find a proof that it is `DataValid`.

**Comment by lodi** [comment]
Thanks @ohad, that explains everything.  I'll document this on the wiki and then close this issue.

**Comment by edwinb** [comment]
I've made a note on this in the README, but I think what @ohad says explains it nicely.
