### ISSUE TITLE
unable to solve constraints 

### ISSUE THREAD

**Issue by vfrinken** [edwinb/Idris2-boot#194]
If possible, please include complete self contained source files (for example by uploading to https://gist.github.com) that exhibit the issue in addition to quoting from them here. The smaller the example the better!

# Steps to Reproduce

Given a list of elements instantiated with a function, the `Here` constructor of the `Elem` data type cannot match.

```
data Elem	 : 	a -> List a -> Type where
    Here	 : 	Elem x (x :: xs)
    There	 : 	(later : Elem x xs) -> Elem x (y :: xs)


data TypeWithFunction : Type where
    ABC  : (ty_a:Type) -> (ty_b:Type) -> (ty_a -> ty_b) -> TypeWithFunction

isInList : Elem (ABC Bool String (\c => if c then "Foo" else "Bar"))
                [(ABC Bool String (\c => if c then "Foo" else "Bar"))]
isInList = Here
```

# Expected Behavior
should compile fine, it does in Idris

# Observed Behavior
Error message 
```
Can't solve constraint between:
	if c then "Foo" else "Bar"
and
	if c then "Foo" else "Bar"
```

**Comment by edwinb** [comment]
This is because both the if/then/elses elaborate via a case block, which elaborates to a top level function, and it'll be a different function in each case, even if the definition is the same. So the type checker has to look inside the function. Idris 1 does, but Idris 2 doesn't, yet. I'll make this work eventually - there is a workaround, which is to manually lift the if block out to a top level function, and use that in the type.

**Comment by edwinb** [comment]
Hmm, turns out it's a little bit more complicated than that in Idris 2 after all. I'll dig deeper...
