### ISSUE TITLE
Ambiguous elaboration when using (>>=) as a data constructor

### ISSUE THREAD

**Issue by ska80** [edwinb/Idris2-boot#204]
# Steps to Reproduce

`Cmd.idr`:

```idris
data MyCmd : Type -> Type where
  Display : String -> MyCmd ()
  Input : MyCmd String

  Pure : ty -> MyCmd ty
  (>>=) : MyCmd a -> (a -> MyCmd b) -> MyCmd b

runMyCmd : MyCmd a -> IO a
runMyCmd (Display str) = putStrLn str
runMyCmd Input = do str <- getLine
                    pure str
runMyCmd (Pure x) = pure x
runMyCmd (c >>= f) = do res <- runMyCmd c
                        runMyCmd (f res)

myCmdTest : MyCmd ()
myCmdTest = do Display "Hello"
               x <- Input
               Display x
               Pure ()
```

```
$ idris2 --check Cmd.idr
```

# Expected Behavior

```
1/1: Building Cmd (Cmd.idr)
```

# Observed Behavior

```
1/1: Building Cmd (Cmd.idr)
Cmd.idr:13:11--13:18:While processing left hand side of Main.runMyCmd at Cmd.idr:13:1--16:1:
Ambiguous elaboration. Possible correct results:
	Builtin.Unit Main.>>= Builtin.Unit
	\{_:188} => \x => Builtin.Unit
```

But it typechecks in Idris 1:

```
idris --check Cmd.idr
```

**Comment by edwinb** [comment]
It turns out this was due to me forgetting about a case on the lhs, it should certainly work the same as Idris 1 here, because the expected type is concretely known to be Cmd.

Although, just for the sake of completeness, I should say that an ambiguity being resolved in Idris 1 doesn't necessarily mean it will be resolved in Idris 2. Idris 2 doesn't work nearly as hard, because this is one of the most common sources of slowness and bad error messages in Idris 1, so it gives up much earlier.
