### ISSUE TITLE
Unable to infer implicit arguments for DPair wrapped in a List

### ISSUE THREAD

**Issue by christian-public** [edwinb/Idris2-boot#223]
# Steps to Reproduce

Create a file named `Main.idr` with the following contents:

```
data Name : Type where
  MN : Int -> Name

data IsVar : Name -> List Name -> Type where
  First : IsVar n (n :: ns)
  Later : IsVar n ns -> IsVar n (m :: ns)

data Expr : List Name -> Type where
  CLocal : (prf : IsVar x vars) -> Expr vars

data FunDecl : Type where
  MkFunDecl : (vars : List Name) -> Expr vars -> FunDecl
  -- MkFunDecl : (vars : List Name ** Expr vars) -> FunDecl -- This definition also works


funDeclWorks : List FunDecl
funDeclWorks = [MkFunDecl [MN 0] (CLocal First)]

-- This function does not type-check
dpairFails : List (vars : List Name ** Expr vars)
dpairFails = [([MN 0] ** CLocal First)]

dpairWithExtraInfoWorks : List (vars : List Name ** Expr vars)
dpairWithExtraInfoWorks = [([MN 0] ** CLocal {x=MN 0} (First {ns=[MN 0]}))]
```

Run `idris2 --check Main.idr`. Tested on commit b0d640f.

Unwrapping the `List`-type from `dpairFails` makes the function type-check. Changing `List` to `Maybe` or `IO` does not make it type-check.

# Expected Behavior

I would expect `dpairFails` to type-check.

# Observed Behavior

```
Main.idr:20:26--20:38:Unsolved holes:
Main.{x:182} introduced at Main.idr:20:26--20:38
Main.{ns:183} introduced at Main.idr:20:33--20:38
```

**Comment by edwinb** [comment]
The other interesting thing is that `dpairWithExtraInfoWorks` really shouldn't work, because it should have `ns=[]`.

Anyway, this turns out to be a silly error in unification. We have a concept of "delayed elaboration" for as yet unresolved ambiguities, where the type checker puts a hole in place of the term to come back to later. Here, the list `[MN 0]` isn't immediately resolved when the elaborator gets to it. Sadly, by the time it gets back to it, the unifier has decided to resolve it. However, it shouldn't be resolving delayed elaborators - only holes. So I've told it to not do that.
