### ISSUE TITLE
Matching on erased arguments within an erased function

### ISSUE THREAD

**Issue by ohad** [edwinb/Idris2-boot#229]
# Steps to Reproduce
```
$ cat Case.idr 
import Decidable.Equality

0 foo : (i, j : Nat) -> Bool
foo i j = case decEq i j of
            Yes pf => True
            No  pf => False
```

# Expected Behavior
```
$ idris2 -c --no-banner Case.idr 
1/1: Building Case (Case.idr)
```

# Observed Behavior
```
$ idris2 -c --no-banner Case.idr 
1/1: Building Case (Case.idr)
Case.idr:4:11--7:1:While processing right hand side of Main.foo at Case.idr:4:1--7:1:
Attempt to match on erased argument Yes pat0: in Main.case block in 1507(292)
```

Since `foo` is itself irrelevant, I'd expect the irrelevance to extend into any case-splits it performs.

**Comment by ohad** [comment]
BTW, until this issue is fixed, I can work around it using a `with` block:
```
$ cat CaseWith.idr 
import Decidable.Equality

0 foo : (i, j : Nat) -> Bool
foo  i j with (decEq i j)
 foo i j | Yes pf = True
 foo i j | No  pf = False
$ idris2 -c --no-banner CaseWith.idr 
1/1: Building CaseWith (CaseWith.idr)
```

**Comment by ziman** [comment]
For some reason, `case` elaboration produces a lifted function with a zero-quantified scrutinee. With `:log 5`, I get:
```idris
LOG 2: Case function type: Main.case block in 1500(292): ((j : Prelude.Nat) -> ((i : Prelude.Nat) -> ((0 {scr:291} : (Prelude.Dec (Builtin.=== Prelude.Nat i[0] j[1]))) -> Prelude.Bool)))
```
Could that be a heuristic that works well for linear values but probably not so well for erased values?

Either way, this is an issue in elaboration, not in the typing rules.

(A small technical note: `foo` is not irrelevant, it's just marked as erasable. "Irrelevance" is usually used for things that are not only erasable at runtime but also ignored in equality.)

**Comment by ziman** [comment]
The case elaborator uses `caseRig` to bind the scrutinee.
```idris
let casefnty =
       abstractFullEnvType fc (allow splitOn env)
           (maybe
               (Bind fc scrn
                   (Pi caseRig Explicit scrty)
                   (weaken caseretty))
               (const caseretty)
               splitOn)
```
In this case, `caseRig = Rig0`, so we observe the behaviour described in the OP.

Normally, the scrutinee will be inspected at least once (constructor tags for the case split), so the quantity of the scrutinee should probably be `max caseRig Rig1`. I don't think it should be `caseRig + Rig1` because the constructor tags are not consumed by the RHSes again so a full-blown sum is not necessary here. For primitives, the RHSes consume nothing so this still holds.

However, if you split on something detaggable, like `Refl`, you don't even consume the tag, so the appropriate quantity would be `caseRig`, I think.

**Comment by ziman** [comment]
It seems `caseRig` does not mean what I thought it did. I'll have a closer look.

**Comment by edwinb** [comment]
This error can only arise from the case tree builder these days, and I think it's because it's unaware that the definition is itself erased so is needlessly worried that it won't have the pattern available at run time...
