### ISSUE TITLE
Idris freezes when trying to implement Biapplicative Pair

### ISSUE THREAD

**Issue by shmish111** [edwinb/Idris2-boot#24]
https://github.com/shmish111/Idris-Bifunctors/blob/master/Data/Biapplicative.idr#L67

# Steps to Reproduce
replace line 68 with `a *>> b = bimap (const id) (const id) <<$>> a <<*>> b`
run `idris2 Data/Biapplicative.idr`

# Expected Behavior
Type checking completes and repl loads

# Observed Behavior
`idris2` process freezes

I've tried to work out which part is causing the issue but I couldn't. I was also unsure how to go about debugging idris2?

**Comment by shmish111** [comment]
Ah, I discovered the problem was because the `Bifunctor Pair` instance wasn't exported. So the issue is that idris2 freezes rather than saying it's not exported.

Question on that, do I need to `export` or `public export` implementations?

**Comment by edwinb** [comment]
I generally make my implementations `export`.

The freezing issue is clearly an important one to look into. I'll take a look. I can't really answer the question about being unsure to go about debugging Idris2, though, because I don't know what you've tried so far... perhaps one possibility is to add %logging directives and see what it's doing at each stage. You'll probably get a lot more than you really need, however.

**Comment by shmish111** [comment]
Wow, that's a lot of info, I'm not sure I can glean any info from that myself.

**Comment by edwinb** [comment]
I don't know which line to replace, because the line in question is the interface header.

In general, a big way to help with debugging issues is to try to get everything into one self contained file, perhaps in a gist, that I can just load. As well as being much quicker and easier for me to reproduce the issue, it reduces the chance that the code has changed by the time I get around to looking at the issue.

**Comment by shmish111** [comment]
OK, I'm not sure if this is related but I've come across another freeze problem in the same code base. Take a look at https://github.com/shmish111/Idris-Bifunctors/blob/master/Data/Bifoldable.idr#L31 apparently that `Monoid` constraint causes the type checker to freeze. I have tried other interfaces including adding a trivial one to the same file but I've now managed to pin it down to the following simple case:
```
module Test

public export
interface F p where
  f : Show a => p a -> a
```
The above will freeze however if we change the return type to something other than the constrained type things work
```
module Test

public export
interface F p where
  f : Show a => p a -> String
```

**Comment by shmish111** [comment]
Ok, sorry about the bad example at the start @edwinb , I've created https://gist.github.com/shmish111/70c8e858801249a08586d8da1303d5f4 with a minimal version of the original problem and https://gist.github.com/shmish111/ce7a0244e75133f9d97bb3d6a51524dd for the second problem.

Maybe you could put in the issue template something asking people to create a gist with the problem? It seems like a very nice way to communicate the issue and it forced me to do a bit of extra work searching for a minimal example!

**Comment by edwinb** [comment]
Okay, I can definitely reproduce it now, thanks! I'll take a closer look. I've also updated the template - anything to reduce the overhead of me being able to reproduce the thing seems to be very effective!

**Comment by edwinb** [comment]
Oh dear, this is intereresting. The problem is that there's no instance for `F String`, but because we have

    interface F a => G a where

...Idris is thinking "oh, I have an instance for `G String` because I'm in the middle of defining it and that means I must have an instance for `F String` because `F a => G a`". And so the circular reasoning goes on. This causes a loop, because Idris inlines interface dictionaries before doing termination checking, which goes on forever here. So, it's kind of amusing, because the thing that stops it terminating is the termination checker.

Anyway, what it's not doing, but should do is make sure that the parent constraint is satisfied before it elaborates the instance for `G String`.

**Comment by shmish111** [comment]
Cool. So this makes it sound like the second issue is completely different. Presumably the termination checker doesn't even do anything with interface definitions. I'm interested to know what the compiler is checking at this point that causes it to (presumably) get in another loop and why it only seems to get stuck when the constrained type is the method return type, it seemingly has no problem if the constrained type is in an argument.

**Comment by edwinb** [comment]
Turns out it's because auto implicit search gets into a loop. It's a bit more complicated than this in the specific case, but imagine you're searching for "X" and you have "f : forall a . a -> a" in scope, it'll keep building f (f (f (f ...))) unless the implicit search realises that using 'f' to build an argument for 'f' is a bad idea.
