### ISSUE TITLE
Delimiters of comments are not properly detected

### ISSUE THREAD

**Issue by vfrinken** [edwinb/Idris2-boot#279]
If I have some code and blocks of comments in between, some code is ignored by the compiler
It doesn't matter whether the comment is in one line `{-- bla --}` or across several lines 
```
{--
multi
line
text
--}
```

# Steps to Reproduce
```Haskell
module Main

{-- comment 1 --}

someFunction : IO ()

{-- comment 2 --}

main : IO ()
main = do
    someFunction
    pure ()
```

# Expected Behavior
that it loads

# Observed Behavior
```
While processing right hand side of main at idrisCommentProblem.idr:11:1--14:1:
Undefined name someFunction
```

**Comment by gallais** [comment]
This is due to #253. It allows us to arbitrarily nest comments because if you
have a valid module then you should be able to comment its content out by simply
adding `{-` and `-}` around it.

`--}` is a valid one-line comment and as such is ignored when parsing the
multiline comment.

If people are really keen on `{------------------` and `-------------------}`
as opening & closing delimiters, we can maybe hook up a special case making
them equivalent to `{-` and `-}` respectively. In which case `--}` would *not*
be a valid commented out line anymore.

ping @ohad

Edit: I have a patch.

**Comment by gallais** [comment]
Grmbl, I think I need yet another special case for `{------------}`.
