### ISSUE TITLE
Add option to compile to CLI

### ISSUE THREAD

**Issue by shmish111** [edwinb/Idris2-boot#29]
# Steps to Reproduce
`idris2 --compile myproject.ipkg`

# Expected Behavior
A chez scheme file is produced (unless you select a different `--codegen`)

# Observed Behavior
`--compile` flag does not exist

The reason for this is that when building an executable that I want to distribute, I don't want to use the REPL or ide interface, especially in a CI system or if using a build and package manager like bazel or nix.

**Comment by edwinb** [comment]
This would be nice, and I know it's something people want, and I am going to do it eventually unless someone else gets there first. Ideally there should also be an option to build an executable via .ipkg files.

I haven't found this sort of thing to be a good use of the issue tracker in Idris 1, though, because they tend to get buried and don't seem to be very discoverable even if we tag effectively. So I end up just getting "argh too many issues" anxiety even though they're more feature requests than bugs. This is why I added the template, in the hope it'd be clear I'd prefer to use the issue tracker to concentrate on where the compiler is misbehaving.

So, perhaps this will work better: I've made a page on the wiki instead - https://github.com/edwinb/Idris2/wiki/Contributions-wanted. I'll also invite suggestions via the mailing list.
