### ISSUE TITLE
Idris 2 should compile itself

### ISSUE THREAD

**Issue by be5invis** [edwinb/Idris2-boot#39]
This is well a general discussion about what is needed for bootstraping Idris 2.

**Comment by edwinb** [comment]
This is already noted on https://github.com/edwinb/Idris2/wiki/Contributions-wanted, and as discussed in #30 and in the issue template, I would rather keep the issue tracker specifically for bug reports at the moment.

**Comment by edwinb** [comment]
I'd also suggest starting a discussion on the mailing list. But mostly it's a matter of working through the code and porting it. I'll do this, in good time. Since the languages are a bit different, it might take a bit of effort, so I won't rush into it, but I have been thinking about it quite a bit.
