### ISSUE TITLE
Can't solve constraint (interface method issue)

### ISSUE THREAD

**Issue by nicolabotta** [edwinb/Idris2-boot#42]
The program
```
module issues.CannotSolveConstraint2

import Data.Fin
import Data.Vect

toVect : {A : Type} -> {n : Nat} -> (Fin n -> A) -> Vect n A

record Iso a b where
  constructor MkIso
  from : b -> a

interface Finite t where
  card : Nat
  iso  : Iso t (Fin card)  
  foo : Vect card t
  foo = toVect (from iso)
```
type checks fine in Idris1 but not in Idris2. 

The issue seems to be that, in Idris2,  `card` in the signature of `foo`is not taken to be the `card` method of the interface but an implicit argument.

**Comment by edwinb** [comment]
This is indeed because it's treating `card` as an implicit rather than updating it to refer to the interface method. I have a fix coming shortly.

Note, though, that because of the QTT core you'll need to update the type of `toVect` to:

    toVect : {0 A : Type} -> {n : Nat} -> (Fin n -> A) -> Vect n A

Or alternatively you could write

    toVect : forall A .  {n : Nat} -> (Fin n -> A) -> Vect n A

...because `t` is erased in the body of `Finite` and the type of `toVect` suggests that it's going to be used, even though it isn't needed.

**Comment by nicolabotta** [comment]
Interesting, what about `{n : Nat}`? is it also an argument that "is used but not needed"? In which sense?

Is there some introduction to the new notation for Idris practitioners? I read the intro of the Atkey paper but I am nut sure that I have a good intuition of what is used/needed at type checking time and what is used/needed at run-time!

**Comment by edwinb** [comment]
`{n : Nat}` is needed because (at least in the code you sent me separately) it pattern matches on the `n`.

I haven't written up the details of the notation yet, beyond the examples in the test suite. I need to update the existing tutorial for Idris 2, which is where it'll be. 

But, in general, every variable has a quantity, either 0, 1, or any. 'any' is equivalent to Idris 1's behaviour. Informally the rules are:

* if you don't give a quantity in an argument, it's considered "any"
* otherwise you can write `(0 x : T)`, `(1 x : T)`, `{0 x : T)`, `{1 x : T}` to explicitly state 0 (erased) or 1 (used exactly once)
* You can also write forall x . S, to say that `x` has quantity 0
* Unbound implicits have quantity 0
* If anything has quantity 0, the type checker must be able to prove that it's unused at run time. Generally this means there is no pattern matching on it in a function, and no use of it in anything that function calls

**Comment by nicolabotta** [comment]
Thanks Edwin, for the time being that's enough information for me to get started! Best, N.
