### ISSUE TITLE
Can't find an implementation for Functor

### ISSUE THREAD

**Issue by nicolabotta** [edwinb/Idris2-boot#49]
The program
```
module issues.CannotFindImplementation

public export
interface Monad m => FooBar m where

  Foo    : {A : Type} -> A -> m A -> Type

  bar    : {A : Type} -> (ma : m A) -> m (DPair A (\ a => Foo a ma))

  foobar : {A : Type} -> (ma : m A) -> map fst (bar ma) = ma
```
fails to type check in Idris2 with
```
issues.CannotFindImplementation> :r
1/1: Building issues.CannotFindImplementation (issues/CannotFindImplementation.idr)
issues/CannotFindImplementation.idr:10:40--10:57:While processing constructor issues.CannotFindImplementation.FooBar at issues/CannotFindImplementation.idr:3:1--13:1 at issues/CannotFindImplementation.idr:3:1--13:1:
Can't find an implementation for Functor m
issues.CannotFindImplementation>
```
The same error occurs if one replaces
```
interface Monad m => FooBar m where
```
with
```
interface Functor m => FooBar m where
```
The error message is triggered by `map` in the signature of `foobar`. It seems like an Idris2 bug to me given that `map` is a method of the `Functor` interface.

**Comment by edwinb** [comment]
There is indeed a Functor available, but it looks like it's refusing to use it because I was trying to be too clever with quantities in interface declarations. This is easily fixable, though I'd like to think a bit more carefully about how things are fitting together before I push a fix.

By the way, `fst` is going to be treated as an implicit argument in the type of `foobar`, following the usual rules that it's a name beginning with a lower case letter that isn't applied to anything. If this works in Idris 1, it shouldn't. I'll implement `%auto_implicits off` at some point and add a warning for this sort of thing.

**Comment by nicolabotta** [comment]
Thanks Edwin, it would indeed be great to have an `%auto_implicits off` switch in Idris 2!
