### ISSUE TITLE
INTERNAL ERROR: Can't write resolved name

### ISSUE THREAD

**Issue by kevinboulain** [edwinb/Idris2-boot#55]
### Steps to Reproduce

`idris2 --check example.idr`

**EDIT**: on commit 19a0795

```idris
interface Interface specifier where
  0 concrete : specifier -> Type

record Value s where
  constructor MkValue
  specifier : s

0 DependentValue : Interface s => Value s -> Type
DependentValue v = concrete (specifier v)

-- Can't find an implementation for Interface s
-- record Record s where
--   constructor MkRecord
--   value : Value s
--   dependentValue : DependentValue {s} value

-- INTERNAL ERROR: Can't write resolved name 1102
data Record : s -> Type where
  MkRecord : Value s -> DependentValue {s} value -> Record s

data Specifier = SBool | SString

implementation Interface Specifier where
  concrete SBool = Bool
  concrete SString = String

-- This is ok
0 TestSpecifier : Type
TestSpecifier = DependentValue (MkValue SBool)
t : TestSpecifier
t = True
```

### Expected Behavior

I'm probably doing something stupid but I was trying to get the a `record` work with a constrained interface, see above example for a simplified example.

### Observed Behavior

The goal was to get the type of the `dependentValue` field in `Record` computed from the other `value` field and constrained by `Interface`.

The record was failing with `Can't find an implementation for Interface s` (which didn't really surprise me because the constraint is on the `DependentValue`, not the record, and I think there was some related limitations in Idris 1?).
So I tried to write the record without syntactic sugar as `data` but got this internal error.

Feel free to close the issue if can't do anything about it.

**Comment by christian-public** [comment]
You are very close to a solution. I got the following versions of `data Record` and `record Record` to work:

```
data Record : Type -> Type where
  MkRecord : Interface s => (value : Value s) -> DependentValue value -> Record s

testRecord : Record Specifier
testRecord = MkRecord (MkValue SBool) True


record Record2 s where
  constructor MkRecord2
  {prf : Interface s}
  value : Value s
  dependentValue : DependentValue value

testRecord2 : Record2 Specifier
testRecord2 = MkRecord2 {prf = %search} (MkValue SBool) True
```

## `data Record`

The difference from your version:
- Changed `a -> Type` to `Type -> Type` in the type constructor.
- Added `Interface s =>` (which is required by `DependentValue`).
- Added a name to the `(value : Value s)` parameter, so that `DependentValue value` knows what it depends on.


## `record Record`

The difference from your version:
- Added the implicit field `{prf : Interface s}` (which can now be written as the first field because of a recent fix by @clayrat: https://github.com/edwinb/Idris2/issues/46 🎉).
- Removed `{s}` from `DependentValue value`.

It is a bit inconvenient that one needs to be explicit about the `prf` argument in the `testRecord2` case. Based on the following test file: [Record.idr](https://github.com/edwinb/Idris2/blob/master/tests/idris2/record001/Record.idr), it seems like one should not need to provide a value, but in this case the compiler is not able to infer a value. I am guessing that the difference has something to do with the difference between implicit arguments and auto-implicit arguments. Does it make sense to allow `{auto prf : Interface s}` in record definitions? 🤔

**Comment by kevinboulain** [comment]
Thanks for taking a look!
I think I tried the implicit in in the record but I missed the `%search`.
For the data, I must admit I kinda gave up after being stuck with the internal error :)

In my version, I still have have to specify the implicits for `DependentValue` in the record and the data (I have one more type in `Interface` and I can't really figure out how to make everything happy). So there is something different between the data and record that doesn't require to specify the `%search` for the data.

We can probably close the issue, it was more of an error on my side I guess.

**Comment by edwinb** [comment]
I'd still leave this open - the internal error message hints that something funny is going on. I haven't looked at any of the other details yet though...

**Comment by edwinb** [comment]
It turns out that, in types, it's not checking whether auto implicits are resolved. It's okay to leave holes in types (because they might be resolved by the definition) but not auto implicits, so I'm adding a check for this.
