### ISSUE TITLE
High CPU/memory requirement compiling Vector indexing code

### ISSUE THREAD

**Issue by ysangkok** [edwinb/Idris2-boot#58]
# Steps to Reproduce

```
import Data.Vect

test : Vect 33 Int -> IO Int
test bytes_list = do
  let int1 = (index 0 bytes_list * 8) + (index 1 bytes_list * 4) + (index 2 bytes_list * 2) + (index 3 bytes_list)
  let int2 = (index 4 bytes_list * 8) + (index 5 bytes_list * 4) + (index 6 bytes_list * 2) + (index 7 bytes_list)
  let int3 = (index 8 bytes_list * 8) + (index 9 bytes_list * 4) + (index 10 bytes_list * 2) + (index 11 bytes_list)
  let int4 = (index 12 bytes_list * 8) + (index 13 bytes_list * 4) + (index 14 bytes_list * 2) + (index 15 bytes_list)
  pure $ int1 + int2 + int3 + int4
```

# Expected Behavior

Should compile quickly, nothing fancy here.

# Observed Behavior

Seems to just hang at 100% CPU utilization. A previous version of this program triggered my OOM-killer...

Interestingly, if I remove two of the ints, it seems to compile. I tried compiling with gprof and using valgrind with the massif tool, but I can't figure out why the compiler gets stuck.

**Comment by edwinb** [comment]
It's not fancy, but the Nat and Fin literals do make it pretty big, which is probably at least part of the cause. I'm slightly surprised that Idris 1 can get through this... so maybe it's an indication of some deeper problem.

It's also interesting that the performance doesn't seem to be linear in the number of ints.

One thing I want to do eventually is teach the elaborator about Nats so that it can handle much bigger literals at type checking time. But I'd also like it to be fast enough that that sort of optimisation isn't necessary for this kind of example.

**Comment by edwinb** [comment]
Also interestingly, I tried a little experiment with the elaborator, to change it so that let bindings don't have computational force during typechecking, and it elaborated pretty much straight away. I went up to 10 integers, and there's a little bit of a pause due to all the Nats but it's still fine...

I don't think that's the behaviour we want for let. but at least it hints at what might be going wrong.

**Comment by edwinb** [comment]
Okay, I say it's not the behaviour we want, but I have been wondering about this for some time and this example is the thing that finally convinces me to change things. `let` bindings already lose their computational behaviour when going inside case or with blocks, and it's probably best that it's consistent everywhere. One of the main purposes of `let` is to help preserve sharing for large expressions, and if the elaborator substitutes the value then sharing is broken.

If you do need `let` to have computational behaviour in types, you can always make a local function definition. Otherwise, now, `let x = v in e` is now equivalent to `(\x => e) v`.
