### ISSUE TITLE
Infinite loop with hole

### ISSUE THREAD

**Issue by kevinboulain** [edwinb/Idris2-boot#6]
Hi there,

Just to let you know, there is an infinite loop (100% CPU utilization) when a hole reuse a name:
```idris
example : String
example = ?example
```

Tested on commit 1cf9849.

Thank you for Idris 2 :)

**Comment by edwinb** [comment]
Oops, yes, good point! This is because it should reject the hole name because the name already exists. I have been meaning to add a check that holes are given names which are not already defined, but I haven't yet...

I'll probably do this soon, but if anyone is looking for a thing to do to help find their way around the code, this is not a bad place to start!

**Comment by googleson78** [comment]
I would like to take a look at this next week, if nobody else has yet.

**Comment by ysangkok** [comment]
@googleson78 did you give up?

**Comment by googleson78** [comment]
@ysangkok
Go ahead, I overestimated my free time :( sorry

**Comment by edwinb** [comment]
I'm taking a look at this - it turns out to be a little bit trickier than I first thought.
The main thing is that in TTImp.Elab.Hole, it needs to check that the hole name you give is not yet defined, in the same way it checks every other place where a definition can be introduced. But the thing I forgot is that interactive editing introduces holes, and in particular generating complete definitions from types introduces lots of holes on the way, and it turns out I hadn't taken care to make sure they were unused names. It didn't really matter in that case, because it just prints the definition and returns to the previous state, but for the sake of neatness I will tidy that up.
