### ISSUE TITLE
Using Data.Vect.index too expensive (maybe Fin problem?)

### ISSUE THREAD

**Issue by ysangkok** [edwinb/Idris2-boot#63]
# Steps to Reproduce

On commit 56a09b033f8eddf38168a60f53cfdd48716075f1

```
module TooSlow

import Data.Vect

test : Vect 1 () -> IO ()
test b = do
  let i = index 1 b
  let i = index 1 b
  let i = index 1 b
  let i = index 1 b
  let i = index 1 b
  let i = index 1 b
  let i = index 1 b
  let i = index 1 b
  let i = index 1 b
  let i = index 1 b
  pure ()

main : IO ()
main = do
  pure ()
```

# Expected Behavior

Should compile and run quickly.

# Observed Behavior

Needs more than 10 seconds to compile, don't know how long it would need.

**Comment by edwinb** [comment]
It's curious that it's the last two `let`s when it starts to break. I'm not sure it's anything to do with `Fin` directly, especially since it's still a problem when changing the integer literal to `Fin` constructors directly.

By the way, it either needs to be `Vect 2` or the literal needs to be `1` for this to type check.

**Comment by edwinb** [comment]
yeah, it's definitely the way `let` is elaborated, because I just tried an experiment that made it elaborate essentially immediately, as it should. I'll think some more about the right way to proceed.
