### ISSUE TITLE
Cannot solve constraint: bug or expected behavior

### ISSUE THREAD

**Issue by nicolabotta** [edwinb/Idris2-boot#67]
The program
```
module issues.CannotSolveConstraint3

Surjective : {s, t : Type} -> (f : s -> t) -> Type
Surjective {s} {t} f = (y : t) -> DPair s (\ x => f x = y)

NonSurjective : {s, t : Type} -> (f : s -> t) -> Type
NonSurjective {s} {t} f = DPair t (\ y => (x : s) -> Not (f x = y))

nonSurjectiveNotSurjective : {s, t : Type} -> (f : s -> t) -> NonSurjective f -> Not (Surjective f)
nonSurjectiveNotSurjective f (MkDPair y faxnfxy) =
  \ surjectivef => let x = fst (surjectivef y) in (faxnfxy x) (snd (surjectivef y))
```
type checks in Idris 1 but in not in Idris 2:
```
 nicola@cirrus:~/gitlab/botta/Idris2Libs$ idris2 issues/CannotSolveConstraint3.idr
1/1: Building issues.CannotSolveConstraint3 (issues/CannotSolveConstraint3.idr)
issues/CannotSolveConstraint3.idr:11:64--11:83:While processing right hand side of issues.CannotSolveConstraint3.nonSurjectiveNotSurjective at issues/CannotSolveConstraint3.idr:10:1--13:1:
Can't solve constraint between:
	fst (surjectivef y)
and
	x
Welcome to Idris 2 version 0.0. Enjoy yourself!
issues.CannotSolveConstraint3>
```
Is this the expected behavior or an Idris 2 issue?

**Comment by edwinb** [comment]
Argh. This is because I changed the behaviour of `let` for performance reasons so that `let x = t in e` is now essentially the same as `(\x => e) t`. If it reduces arbitrarily in the scope, it can break sharing massively especially now that unification problems are represented as applications of metavariables to the environment (so a bigger environment has all the let bound things substituted in, which hurts). See #58 for an example of what goes wrong.

I was wondering how long before something came up that would be affected by this. At the moment, you can make this work as follows:

    nonSurjectiveNotSurjective : {s, t : Type} -> (f : s -> t) -> NonSurjective f
    nonSurjectiveNotSurjective f (MkDPair y faxnfxy) =
      \ surjectivef => let x : ?
                           x = fst (surjectivef y) in
                               (faxnfxy x) (snd (surjectivef y))

This works because this form of `let` gets lifted to a top level function, so has computational behaviour, and doesn't get captured in the local environment of metavariables so won't affect performance. But I don't like this solution - the original code ought to work.

I don't yet know the best way out here. There's a lot of constraints, and I'm absolutely not willing to compromise on performance so #58 and #63 have to be resolved. I will think carefully about what to do.

**Comment by nicolabotta** [comment]
Thanks Edwin, I am perfectly fine with this solution, feel free to close the issue if you do not need it anymore.

**Comment by edwinb** [comment]
I'm not especially keen on this solution, although I'm glad it works!
I am currently inclined to keep the behaviour of `let` as it is, though, because even though it's weaker than Idris 1, it is at least consistent everywhere. As things are, it's bordering on impossible to preserve the computational behaviour of `let` when going under a `case` (and therefore also when doing dependent record update) while also maintaining the behaviour that lets don't break sharing. That's a weakness of the elaborator, which I'd like to fix, but it's probably one to come back to much later.

We should be able to come up with a better notation than the workaround here, at least.

**Comment by edwinb** [comment]
I'm just revisiting some old issues, and while I'm not tremendously happy about the solution to this one, I think it's the one we should go with (and the change in `let` behaviour is documented now, at least, at https://idris2.readthedocs.io/en/latest/updates/updates.html#let-bindings). So I think I should close this.
