### ISSUE TITLE
Can't find an implementation

### ISSUE THREAD

**Issue by nicolabotta** [edwinb/Idris2-boot#77]
The program
```
import Control.Monad.Identity

public export
interface Foo (sA : Type) where
  A : Type
  Elem : A -> sA -> Type
  Empty : sA -> Type
  Empty as = (a : A) -> Not (Elem a as)

public export
implementation Foo (Identity Bool) where
  A = Bool
  Elem x (Id y) = x = y
```
fails to type check with
```
nicola@lt561:~/gitlab/botta/Idris2Libs$ idris2 issues/CannotFindImplementation1.idr
1/1: Building issues.CannotFindImplementation1 (issues/CannotFindImplementation1.idr)
issues/CannotFindImplementation1.idr:10:1--18:1:While processing right hand side of Main.Empty at issues/CannotFindImplementation1.idr:10:1--18:1:
Can't find an implementation for Foo ?sA
Welcome to Idris 2 version 0.0. Enjoy yourself!
Main>
```
The program can be made to type check by commenting out the implementation of `Empty` in the `Foo` interface. This seems like an Idris 2 bug to me: the expected behavior would be that the program type checks.

**Comment by edwinb** [comment]
I've finally had a look at this one. The problem is in the way it generates the definition of `Empty` in the implementation of `Foo`. It should be:

    Empty as = (a : A {sA = Identity Bool}) -> Not (Elem a as)

(Or an equivalent which makes it explicit that it's talking about the `A` for the present implementation). However, instead, it merely generates:

    Empty as = (a : A) -> Not (Elem a as)

As a result, it doesn't know which `A` it's looking for.
This is theoretically easy to fix. I'll do it next and see if it's also easy to fix in practice...
