### ISSUE TITLE
can't infer type in where clause

### ISSUE THREAD

**Issue by shmish111** [edwinb/Idris2-boot#79]
See https://gist.github.com/shmish111/02b71edf3e289bcc2ee9f48d55aac86f

# Steps to Reproduce
`idris C.idr`

# Expected Behavior
Module compiles

# Observed Behavior
```
C.idr:7:9--7:17:While processing right hand side of C.f at C.idr:4:1--7:17:
No type declaration for C.f'
```

I'm not sure if this is expected or not but it's at least a "type inference regression" from Idris 1 😢

**Comment by edwinb** [comment]
This is correct. I deliberately decided not to implement this because it's too unpredictable. Maybe if we can work out appropriate rules, it'll be fine some time later, but Idris 1 has far too much magic and I'd rather not have any magic at all...

So, I'm going to close this is expected behaviour, sorry.
