### ISSUE TITLE
Not a valid implicit argument

### ISSUE THREAD

**Issue by nicolabotta** [edwinb/Idris2-boot#8]
The program
```
module Implementation

import Data.Fin

interface Foo t where
  foo : Nat

implementation Foo (Fin n) where
  foo {n} = n
```
type checks fine in Idris but not in Idris 2:
```
nicola@lt561:~/gitlab/botta/Idris2Libs/issues$ idris2 Implementation.idr 
1/1: Building Implementation (Implementation.idr)
Implementation.idr:9:3--9:11:While processing left hand side of Implementation.foo at Implementation.idr:9:3--10:1:
n is not a valid implicit argument in foo
Welcome to Idris 2 version 0.0. Enjoy yourself!
```

**Comment by christian-public** [comment]
~~Note that you could in theory use the variable `n` directly (without specifying `{n}` on the left-hand side): "Names which are in scope in a type are also always in scope in the body of the corresponding definition." (from README.md), but since unbound implicit variables will have multiplicity of 0 (ref. Notes/implementation-notes.md) you won't be able to use this variable.~~
EDIT: I guess this is not relevant in this case.

The following trick worked in Blodwen, but I don't have `idris2` in front of me so I can't verify it now:
```
implementation (n : Nat) => Foo (Fin n) where
  foo {n} = n
```

As far as I understand, in Blodwen (and Idris2) `(n : Nat) =>` behaves like `{auto n : Nat} ->` (I don't know what the exact difference is), so the compiler will look for an appropriate value for `n`. The variable `n` can now be put into scope as an unrestricted variable.

**Comment by clayrat** [comment]
It seems to compile in Idris2.

**Comment by edwinb** [comment]
Ideally Nicola's program should work as is, but there's a few corners of
the interface code that are still missing. Interesting workaround though, I
hadn't thought of that as a possibility.

**Comment by nicolabotta** [comment]
@chrrasmussen Thanks, the workaround works also in Idris 2. The drawback is that it doesn't work in Idris 1. 

Anyway, I just wanted to document the problem. From my point of view it is not an urgent issue and it is good to know that the program should work as it is.

**Comment by edwinb** [comment]
This turns out to be quite interesting. The original program works in Idris 1, but I think that's a side effect of a hack in elaboration of interfaces to deal with weaknesses in Idris 1 unification. In general, in Idris 2, if you have an interface...

    interface X a b where
        f : a -> b

...and an implementation with parameters instantiated as S and T...

    X S T where
        f s t = ?stuff

...then when it elaborates the implementation, it will make a type for the implementation of `f` by substituting `S` for `a` and `T` for `b`, then proceeding as normal. So in this case:

    X-impl-of-f : S -> T

In the case of `foo` above, this means we get the following type for the implementation of `foo`:

    foo : Nat

In other words, nothing happened, because there's no `t` to substitute in, so `Fin n` doesn't appear in the type, so there's no `n` in the type to match against. Idris 1 gets around this by taking the implicit bindings from the interface and just adding them to every method, but that leads to more complications in dealing with name clashes. I think I've come up with a way to deal with this in Idris 2 that isn't too complicated, but I'm wondering if it's the right thing to do.

In this case, there's going to be another problem, which is that even if `n` was available, it'd be erased so unusable. In practice, we might actually want to allow that in the case that `foo` is only intended for use in types, and so we might want to allow programs to mark methods as 0 quantity.

In summary, we really need to have a formal description of how implementations are built, beyond just the code! I would like to do that sooner rather than later. There is, unfortunately, little chance that the same code will work in both Idris 1 and Idris 2, and I think it's best we don't make any compromises in trying to do so - I don't want to be dealing with things that are merely the result of bad implementation decisions in the past!

**Comment by edwinb** [comment]
Oh, also, @chrrasmussen's question about the relationship between `(n : Nat) => ` and `{auto n : Nat} ->` reminds me that this works:

    interface Foo t where
      constructor MkFoo
      foo : Nat
  
    %hint
    FooFin : {n : Nat} -> Foo (Fin n)
    FooFin = MkFoo (foo {n})
      where
        foo : {n : Nat} -> Nat
        foo = n

The reason is that there is literally no different between `(n : Nat) =>` and `{auto n : Nat} =>`. The former is syntactic sugar for the latter, and interfaces are implement in /exactly/ the same way as auto implicits. That is, they are merely syntactic sugar for auto implicits and you can always implement instances direclty, like in the example above, if the desugaring turns out not to be powerful enough (except that, at the moment, you need to know the name of the constructor of the interface, but I'll add another way to access this).

In this case, the most tricky bit is probably the need to express that `n` is needed at run-time, which is probably the biggest difference from Idris 1 in the core language. So I've explicitly written the `{n : Nat} ->` in the type for `FooFin` to express that.

So my inclination at the moment is that it's more important to keep the desugaring as simple and explainable as possible for the common case, to reduce the possibility of tricky errors (and, honestly, to keep my workload in maintaining it manageable), because more complex desugarings can always be done by hand.

Incidentally, if you write

    (n : Nat) => Foo (Fin n) where

then the type of `foo` becomes

    foo : {auto n : Nat} -> Nat

because the constraints need to be passed through to the methods in order that implementations can make use of methods in parent interfaces. This might suggest that all the implicits should be passed through as well.

Anyway, clearly there's some design decisions to make here. I'd like to err on the side of "easiest to explain", especially since that probably also means "most likely to work" :)

**Comment by edwinb** [comment]
I think I've convinced myself after all that that implicits really should be passed through, as in my manually desugared version. Apologies for all the rubber ducking on the way :). Though perhaps some of it was useful anyway...

It does rely on coming up with a suitably simple implementation, though. I *think* I have one...

**Comment by edwinb** [comment]
I'm about to push a patch that allows you to express this:

    interface Foo (t : Type) where
      0 card : Nat
      to : t -> Fin card

    implementation Foo (Fin k) where
      card = k
      to = id

The `0` on the declaration of `card` says that it's compile time only, so it's legitimate to use compile time only things like `k` in the impleemntation. It's not quite backwards compatible with Idris 1, unfortunately, but as is going to be usual, that's due to having the erasure explicitly expressed in the types.

**Comment by nicolabotta** [comment]
I do not fully understand what it means for `card` to be "compile time only". If I add a default method
```
  bar : Nat
  bar = S card
```
then `card` is not only used in the type of `to` but also in the implementation of `bar` and the annotation 
```
  0 card : Nat
```
indeed leads to an error. By contrast,
```
module issues.Implementation

import Data.Fin

interface Foo (t : Type) where
  card : Nat
  to   : t -> Fin card

  bar : Nat
  bar = S card
```
type checks fine. But then
```
module issues.Implementation

import Data.Fin

interface Foo (t : Type) where
  card : Nat
  to   : t -> Fin card

  bar : Nat
  bar = S card

implementation Foo (Fin k) where
  card = k
  to = id
```
fails again to type check with
```
issues.Implementation> :r
1/1: Building issues.Implementation (issues/Implementation.idr)
issues/Implementation.idr:12:1--19:1:While processing right hand side of issues.Implementation.bar at issues/Implementation.idr:12:1--19:1:
Can't find an implementation for Foo ?t
```
! Is this the expected behavior? Shall I open a fresh issue? Best, N.

**Comment by edwinb** [comment]
The error message is strange (possibly to do with the order it elaborates methods), but it shouldn't type check because `card` (relevant because you haven't said it's compile time only) can't use `k` (which is compile time only following the rule that it's an unbound implicit)

There is a related thing, which is that while playing with this I noticed I forgot to tell it to check default method implementations at the right multiplicity. But it's definitely right that this shouldn't type check.

**Comment by nicolabotta** [comment]
Thus, how can I state that `k` in 
```
implementation Foo (Fin k) where
```
is not compile-time only? I guess it happens quite offen that types like `Fin n` or `Vect n A` implement an interface that uses `n` for some default methods!

**Comment by edwinb** [comment]
Yes, this is an interesting problem that we need to work out an answer to... it is possible to say:

    implementation (k : Nat) => Foo (Fin k) where

But that only works by accident and will probably have some odd behaviour in practice. Perhaps some syntax like

    implementation {k : Nat} -> Foo (Fin k) where

?

Sorry that you're the guinea pig here, to some extent... I guess we're all learning how QTT and interfaces interact. I expect there's a paper in it at the end of this!

**Comment by nicolabotta** [comment]
Thanks Edwin, the second approach
```
implementation {k : Nat} -> Foo (Fin k) where
```
seems quite natural to me. In Idris 1 we sometimes had implementations nested in `using` blocks, I guess that could be syntactic sugar for something like the above. Best, Nicola
